spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202204a
    username: postgres
    password: postgres
  jmx:
    default-domain: ec-202204a
  mail:
    host: smtp.gmail.com
    port: 587
    username: r9r.celtics.t9t@gmail.com
    password: ${WIN_EMAIL_PASSWORD}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
server:
  servlet:
    context-path: /ec-202204a